begin;
create table if not exists public.jarvis_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  chat_id bigint not null,
  role text not null check (role in ('user','assistant')),
  body text not null check (length(body) between 1 and 12000),
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists jarvis_chat_messages_lookup_idx on public.jarvis_chat_messages(user_id, chat_id, created_at desc, id desc);
alter table public.jarvis_chat_messages enable row level security;
revoke all on public.jarvis_chat_messages from public, anon, authenticated;
grant select, insert, delete on public.jarvis_chat_messages to service_role;
commit;
